# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

objective_global <- function(beta, x, y, lam1, lam2, lam3, w, intercept) {
    .Call(`_sparseGFL_objective_global`, beta, x, y, lam1, lam2, lam3, w, intercept)
}

objective_local <- function(beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, intercept) {
    .Call(`_sparseGFL_objective_local`, beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, intercept)
}

objective_blocks <- function(beta, x, y, lam1, lam2, lam3, w, wprev, bprev, wnext, bnext, intercept) {
    .Call(`_sparseGFL_objective_blocks`, beta, x, y, lam1, lam2, lam3, w, wprev, bprev, wnext, bnext, intercept)
}

trivial_local <- function(beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, intercept, tol) {
    .Call(`_sparseGFL_trivial_local`, beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, intercept, tol)
}

trivial_mm <- function(lam1, lam2, L, z, wprev, bprev, wnext, bnext, intercept, N, tol) {
    .Call(`_sparseGFL_trivial_mm`, lam1, lam2, L, z, wprev, bprev, wnext, bnext, intercept, N, tol)
}

fp1_vec <- function(beta, L, z, lam1, lam2, w, bprev, intercept, N, maxit, tol) {
    .Call(`_sparseGFL_fp1_vec`, beta, L, z, lam1, lam2, w, bprev, intercept, N, maxit, tol)
}

fp2_vec <- function(beta, L, z, lam1, lam2, wprev, bprev, wnext, bnext, intercept, N, maxit, tol) {
    .Call(`_sparseGFL_fp2_vec`, beta, L, z, lam1, lam2, wprev, bprev, wnext, bnext, intercept, N, maxit, tol)
}

FISTA_1 <- function(beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, L, intercept, maxit_fista, tol_fista, maxit_fp, tol_fp, tol_equal) {
    .Call(`_sparseGFL_FISTA_1`, beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, L, intercept, maxit_fista, tol_fista, maxit_fp, tol_fp, tol_equal)
}

FISTA_M <- function(beta, x, y, lam1, lam2, lam3, w, intercept, startc, endc, eta, maxit, tol_fista, tol_equal) {
    .Call(`_sparseGFL_FISTA_M`, beta, x, y, lam1, lam2, lam3, w, intercept, startc, endc, eta, maxit, tol_fista, tol_equal)
}

grad_cpp <- function(beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, intercept) {
    .Call(`_sparseGFL_grad_cpp`, beta, x, y, lam1, lam2, lam3, wprev, bprev, wnext, bnext, intercept)
}

pg_cpp <- function(z, fixg, lam1, lam2, w, maxit, tol) {
    .Call(`_sparseGFL_pg_cpp`, z, fixg, lam1, lam2, w, maxit, tol)
}

compare_cols <- function(x, tol) {
    .Call(`_sparseGFL_compare_cols`, x, tol)
}

all_equal <- function(x, y, tol) {
    .Call(`_sparseGFL_all_equal`, x, y, tol)
}

objective_global_svar <- function(A, x, y, lam1, lam2, lam3, w, intercept) {
    .Call(`_sparseGFL_objective_global_svar`, A, x, y, lam1, lam2, lam3, w, intercept)
}

objective_local_svar <- function(A, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, intercept) {
    .Call(`_sparseGFL_objective_local_svar`, A, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, intercept)
}

objective_blocks_svar <- function(A, x, y, lam1, lam2, lam3, w, wprev, Aprev, wnext, Anext, intercept) {
    .Call(`_sparseGFL_objective_blocks_svar`, A, x, y, lam1, lam2, lam3, w, wprev, Aprev, wnext, Anext, intercept)
}

trivial_local_svar <- function(x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, lag0, intercept, tol) {
    .Call(`_sparseGFL_trivial_local_svar`, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, lag0, intercept, tol)
}

trivial_mm_svar <- function(lam1, lam2, L, Z, wprev, Aprev, wnext, Anext, lag0, intercept, tol) {
    .Call(`_sparseGFL_trivial_mm_svar`, lam1, lam2, L, Z, wprev, Aprev, wnext, Anext, lag0, intercept, tol)
}

fp1_svar <- function(A, L, Z, lam1, lam2, w, Aprev, lag0, intercept, maxit, tol) {
    .Call(`_sparseGFL_fp1_svar`, A, L, Z, lam1, lam2, w, Aprev, lag0, intercept, maxit, tol)
}

fp2_svar <- function(A, L, Z, lam1, lam2, wprev, Aprev, wnext, Anext, lag0, intercept, maxit, tol) {
    .Call(`_sparseGFL_fp2_svar`, A, L, Z, lam1, lam2, wprev, Aprev, wnext, Anext, lag0, intercept, maxit, tol)
}

FISTA_1_svar <- function(A, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, L, lag0, intercept, maxit_fista, tol_fista, maxit_fp, tol_fp, tol_equal) {
    .Call(`_sparseGFL_FISTA_1_svar`, A, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, L, lag0, intercept, maxit_fista, tol_fista, maxit_fp, tol_fp, tol_equal)
}

FISTA_M_svar <- function(A, x, y, lam1, lam2, lam3, w, lag0, intercept, startc, endc, eta, maxit, tol_fista, tol_equal) {
    .Call(`_sparseGFL_FISTA_M_svar`, A, x, y, lam1, lam2, lam3, w, lag0, intercept, startc, endc, eta, maxit, tol_fista, tol_equal)
}

grad_svar <- function(A, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, lag0, intercept) {
    .Call(`_sparseGFL_grad_svar`, A, x, y, lam1, lam2, lam3, wprev, Aprev, wnext, Anext, lag0, intercept)
}

compare_slices <- function(x, tol) {
    .Call(`_sparseGFL_compare_slices`, x, tol)
}

AXY_elnet <- function(x, y, lambda, alpha, intercept, diag0, eps, maxit) {
    .Call(`_sparseGFL_AXY_elnet`, x, y, lambda, alpha, intercept, diag0, eps, maxit)
}

